services:
  db:
    image: postgres:18
    environment:
      POSTGRES_USER: kiromoku
      POSTGRES_PASSWORD: kiromoku1234
      POSTGRES_DB: kiromoku
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql
volumes:
  db-data:
